### ISSUE TITLE
안녕하세요 ^^

### ISSUE THREAD

**Issue by hadesleee** [nolboo/nolboo.github.io#6]
안녕 하세요 놀부님 블로그 잘 보고 있습니다.
열심히 보다 보니 저도 욕심이 생겨서 글을쓰고 싶다는 생각이 들더군요.
그래서 지킬로 지킬링을 하려고 설치를 했는데 기본 테마가 너무 볼품이 없어서
놀부님 테마를 쓰고싶은데 사용해도 되는지 여쪄보는겁니다.
그럼 좋은 하루 보내세요

**Comment by nolboo** [comment]
얼마든지 사용하셔도 됩니다^^ 즐건 하루 되세요~

**Comment by hadesleee** [comment]
감사합니다. ^^
