### ISSUE TITLE
질문합니다

### ISSUE THREAD

**Issue by roeniss** [nolboo/nolboo.github.io#8]
안녕하세요 웹 입문한 학생입니다.
이런 좋은 번역자를 이제야 알게 되서 많이 배워가려고 하는데요
html&css  중급강좌가 4강 6강 두개만 번역이 되어있는것 같은데
나머지는 별로 의미 없다고 보시나요? 아니면 긴급한 부분만 먼저 처리를 하신건가요? 
학습하는 입장에서 어떤 식으로 접근해야 할 지 알고 싶습니다.

**Comment by nolboo** [comment]
나머지도 모두 좋은 강좌입니다. 그러나, 번역 도중에 중급 강좌의 원문을 변경되어서 다시 번역하기도 그렇고 다른 일 때문에 번역도 진행하기 힘들어졌습니다. 전체를 다 번역하는 것이 과연 좋을까하는 의문도 들기도 했습니다. 좋은 강좌를 소개하는 데에 더 목적을 두기로 하고 나머지는 번역하지 않았습니다. 질문을 이제야 봐서 늦게 답장드립니다. 도움이 되시면 좋겠습니다^^
